DROP TYPE cash.ft_goods ;

CREATE TYPE cash.ft_goods AS (
    ft_id int4,
    ft_date date,
    ft_time time,
    ft_type int4,
    ft_wrkplace int4,
    ft_doc_num int4,
    ft_cashier_id int4,
    ft_item_code varchar,
    ft_txt09 varchar,
    ft_price numeric,
    ft_qnt numeric,
    ft_sum numeric,
    ft_receipt_type int4,
    ft_shift_num int4,
    ft_rounded_sum numeric,
    ft_disc_sum numeric,
    ft_print_group varchar,
    ft_item_article varchar,
    ft_barcode int4,
    ft_sum_no_disc numeric,
    ft_int21 int4,
    ft_int22 int4,
    ft_doc_code varchar,
    ft_int24 int4,
    ft_int25 int4,
    ft_doc_info varchar,
    ft_int27 int4,
    ft_int28 int4,
    ft_int29 int4,
    ft_txt30 varchar,
    ft_int31 int4,
    ft_int32 int4,
    ft_txt33 varchar,
    ft_mark varchar
);

